[package]
categories = ["cryptography", "development-tools"]
description = "Reproducible software identity and fine-grained build dependency tracking."
keywords = ["gitbom", "omnibor", "sbom"]
name = "omnibor"
readme = "../README.md"
repository = "https://github.com/omnibor/omnibor-rs"
version = "0.4.0"

homepage.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]

# Library dependencies

gitoid = "0.5.0"
tokio = { version = "1.36.0", features = ["io-util"] }
url = "2.5.0"

# Binary-only dependencies

anyhow = { version = "1.0.80", optional = true }
async-walkdir = { version = "1.0.0", optional = true }
clap = { version = "4.5.1", features = ["derive"], optional = true }
futures-lite = { version = "2.2.0", optional = true }
serde_json = { version = "1.0.114", optional = true }
smart-default = { version = "0.7.1", optional = true }

[dev-dependencies]
tokio = { version = "1.36.0", features = ["io-util", "fs"] }
tokio-test = "0.4.3"

[features]
build-binary = [
    "dep:anyhow",
    "dep:async-walkdir",
    "dep:clap",
    "dep:futures-lite",
    "dep:serde_json",
    "dep:smart-default",
    "tokio/fs",
    "tokio/io-std",
    "tokio/macros",
    "tokio/rt",
    "tokio/sync",
    "tokio/time",
    "tokio/rt-multi-thread"
]

[[bin]]
name = "omnibor"
test = false
bench = false
required-features = ["build-binary"]
