[package]
categories = ["cryptography", "development-tools"]
description = "An experimental implementation of gitbom in Rust"
edition = "2021"
homepage = "https://omnibor.io/"
keywords = ["gitbom", "omnibor", "sbom"]
license = "Apache-2.0"
name = "omnibor"
readme = "../README.md"
repository = "https://github.com/omnibor/omnibor-rs"
version = "0.2.0"

[dependencies]
gitoid = "0.2.0"

