[package]

name = "omnibor"
version = "0.5.1"

description = "Reproducible software identity and fine-grained build dependency tracking."
repository = "https://github.com/omnibor/omnibor-rs"
readme = "README.md"
categories = ["cryptography", "development-tools"]
keywords = ["gitbom", "omnibor", "sbom"]

edition.workspace = true
license.workspace = true
homepage.workspace = true

[lib]
crate-type = [
    # Let the Rust compiler choose a "recommended" lib type for use by Rust code.
    "lib",

    # A system-specific static library usable by non-Rust code.
    # This is `*.a` on Linux, macOS, and Windows using the MinGW toolchain.
    # This is `*.lib` on Windows using the MSVC toolchain.
    "staticlib",

    # A system-specific dynamic library usable by non-Rust code.
    # This is a `*.so` file on Linux.
    # This is a `*.dylib` file on macOS.
    # This is a `*.dll` file on Windows.
    "cdylib",
]

[dependencies]

# The async runtime we support.
tokio = { version = "1.36.0", features = ["io-util"] }

# Support conversion of ArtifactId's to and from `gitoid`-scheme URLs.
url = "2.5.0"

# Support serializing and deserializing.
serde = { version = "1.0.197", optional = true }

# Make it easier to define our error type.
thiserror = "1.0.60"

# Make it easier to build paths.
pathbuf = "1.0.0"

# Walk through directories. Used for file system storage.
walkdir = "2.5.0"

[dependencies.gitoid]
version = "0.7.0"
default-features = false
features = ["async", "hex", "sha256", "std", "url"]

[dev-dependencies]

# This just adds the "fs" feature when running tests.
tokio = { version = "1.36.0", features = ["io-util", "fs"] }

# Helper for running tests with the Tokio runtime.
tokio-test = "0.4.3"

# Match the version used in the `gitoid` crate.
digest = "0.10.7"

# Helper for testing Serde implementations.
serde_test = "1.0.176"

# Make it easier to build paths for testing.
pathbuf = "1.0.0"

[features]

# Support serde serialization and deserialization
serde = ["dep:serde", "gitoid/serde"]
